### ISSUE TITLE
Save simulator state and start from it later

### ISSUE THREAD

**Issue by mariogpascual** [tasts-robots/upkie#105]
Hi again! Is it currently possible to save different simulator states and restart from them later?

**Comment by stephane-caron** [comment]
This is not implemented currently, but it is a low-hanging fruit as previously discussed [here](https://github.com/tasts-robots/upkie/discussions/63#discussioncomment-6101737). We could do it as follows:

- Saving the simulator state: read positions (joint angles, base position, base orientation) and velocities (joint velocities, base linear velocity, base angular velocity) from the simulation.
- Restoring the simulator state: pass the saved positions and velocities via the `config` dictionary at spine configuration time.

This feature would result from https://github.com/tasts-robots/upkie/issues/64. If you agree that the two are the same, let's close this issue and continue the discussion there :slightly_smiling_face:

**Comment by stephane-caron** [comment]
On a related note, https://github.com/tasts-robots/upkie/pull/148 adds initial base velocities to Bullet.

The corresponding PR in Vulp was https://github.com/tasts-robots/vulp/pull/61 (a similar change can be applied to reset joint states).
