### ISSUE TITLE
How to remove the realtime constraint? 

### ISSUE THREAD

**Issue by perrin-isir** [tasts-robots/upkie#77]
Hi, in order to train a policy in simulation, I would like to disable the realtime constraint. So far, I commented the `self.__rate.sleep()` line in the step() function.
Is there a better way to do it?

**Comment by stephane-caron** [comment]
@perrin-isir I added some context to the following discussion: https://github.com/tasts-robots/upkie/discussions/79

**Comment by perrin-isir** [comment]
Great, thanks! There may be a small ambiguity with the role of `frequency`: the doc says "Control frequency in Hz.", yet we could want to modify the control frequency even in a simulation with no realtime constraint (it still impacts the simulation since it changes how much we integrate all actions). The question would then be: what sets the frequency of control inputs when `frequency=None`?

**Comment by stephane-caron** [comment]
> The question would then be: what sets the frequency of control inputs when frequency=None?

That would be the ``--nb-substeps`` parameter that the spine is started with, which accompanies the ``--spine-frequency`` parameter. This is detailed e.g. [here](https://github.com/tasts-robots/upkie/discussions/79#discussion-5352168).
